import { Dataset, KnowledgeEdge, KnowledgeNode } from "./types";

const GROUP_COLORS: Record<string, string> = {
  zhuanghe: "#dce3ee",
  docs: "#d4dbe6",
  geology: "#cfd7e4",
  engineering: "#d9dee8",
  regional: "#c8d2dc",
  mining: "#c9d5df",
};

const baseNode = (
  key: string,
  label: string,
  nodeType: string,
  group: string,
  level: number,
  x: number,
  y: number,
  description: string,
  content: string,
  learningValue: string,
  childCount = 0,
  parentKey?: string,
  relationHint?: string,
): KnowledgeNode => ({
  key,
  label,
  nodeType,
  group,
  level,
  x,
  y,
  description,
  content,
  learningValue,
  childCount,
  parentKey,
  relationHint,
  color: GROUP_COLORS[group] || "#d7dde7",
});

const edge = (key: string, source: string, target: string, relation: string): KnowledgeEdge => ({
  key,
  source,
  target,
  relation,
});

export const createMockDataset = (): Dataset => {
  const nodes: KnowledgeNode[] = [
    baseNode(
      "zhuanghe-project",
      "辽宁庄河抽水蓄能电站",
      "项目",
      "zhuanghe",
      0,
      -7.2,
      -1.2,
      "整个知识图谱的主项目节点，也是员工进入项目资料学习的总入口。",
      "从这里可以继续追到可研报告、工程地质勘察报告、工程部位、工程地质问题和区域地质背景。",
      "适合建立全局框架，再向专业章节和细粒度实体钻取。",
      6,
    ),
    baseNode(
      "feasibility-report",
      "可研报告",
      "文档",
      "docs",
      1,
      -5.8,
      -2.8,
      "项目早期论证阶段的核心文档，整合总体布置、建设条件和关键技术判断。",
      "适合作为第一次学习的总览文档，帮助理解工程组成、建设目标与主要风险。",
      "先看可研报告能建立整体框架，再读专业地质章节。",
      3,
      "zhuanghe-project",
      "属于项目文档",
    ),
    baseNode(
      "geology-report",
      "工程地质勘察报告",
      "文档",
      "docs",
      1,
      -5.1,
      1.1,
      "更偏地质专业分析，解释岩性、构造、地下水和工程地质问题。",
      "这是从项目总览走向工程机理与风险判断的关键文档。",
      "适合在理解项目框架后做纵深学习。",
      4,
      "zhuanghe-project",
      "属于项目文档",
    ),
    baseNode(
      "upper-reservoir",
      "上水库",
      "工程部位",
      "engineering",
      1,
      -2.9,
      -3.4,
      "项目关键建筑物之一，重点关注坝址条件、库盆稳定与渗漏风险。",
      "该节点连接地形地貌、水文地质、坝址条件与水库渗漏问题。",
      "帮助把抽象地质概念落到具体工程对象。",
      2,
      "zhuanghe-project",
      "属于工程部位",
    ),
    baseNode(
      "underground-powerhouse",
      "地下厂房",
      "工程部位",
      "engineering",
      1,
      -2.3,
      0.2,
      "地下洞室群的核心建筑物，围岩分类、断裂影响和地应力分析都围绕这里展开。",
      "它是项目知识里最能把岩性、构造、稳定性和设计逻辑串起来的节点。",
      "读懂地下厂房，就读懂了大半个工程地质分析框架。",
      4,
      "zhuanghe-project",
      "属于工程部位",
    ),
    baseNode(
      "project-risks",
      "项目风险总览",
      "专题",
      "engineering",
      1,
      -2.0,
      3.0,
      "把渗漏、边坡、围岩稳定等问题抽象成项目级风险入口。",
      "适合让设计、施工、学习者快速看到最重要的工程问题，而不是先被报告细节淹没。",
      "从风险倒推文档与实体，是理解工程知识的高效路径。",
      3,
      "zhuanghe-project",
      "属于专题入口",
    ),
    baseNode(
      "regional-geology",
      "区域地质背景",
      "背景知识",
      "regional",
      1,
      -8.7,
      2.6,
      "把区域构造、地貌与地层背景作为项目外层知识框架。",
      "项目知识不是孤岛，区域背景会影响多个工程部位与地质问题的判断。",
      "帮助员工把项目放到更大尺度的空间背景中理解。",
      3,
      "zhuanghe-project",
      "属于背景知识",
    ),

    baseNode(
      "project-layout",
      "工程总体布置",
      "章节",
      "docs",
      2,
      -4.2,
      -4.1,
      "说明上水库、下水库、输水系统、地下厂房等如何组成整个工程。",
      "是把项目从总概念拆成多个工程对象的第一层。",
      "适合第一次学习时建立工程结构概念。",
      0,
      "feasibility-report",
      "属于可研报告",
    ),
    baseNode(
      "construction-conditions",
      "建设条件",
      "章节",
      "docs",
      2,
      -4.0,
      -2.0,
      "从场地、交通、地形、地质和水文等角度说明项目建设条件。",
      "帮助理解为什么这个项目的方案不是任意选择出来的。",
      "是从项目概念走向约束条件的过渡节点。",
      0,
      "feasibility-report",
      "属于可研报告",
    ),
    baseNode(
      "scheme-comparison",
      "方案比选",
      "章节",
      "docs",
      2,
      -3.9,
      -0.1,
      "把多个工程方案进行比较，体现决策依据。",
      "这里通常会把工程布置、风险、投资与实施条件放在一起比较。",
      "适合管理和技术视角对齐。",
      0,
      "feasibility-report",
      "属于可研报告",
    ),

    baseNode(
      "topography",
      "地形地貌",
      "章节",
      "geology",
      2,
      -2.0,
      -1.8,
      "解释山地、沟谷、坡体等形态如何约束工程布置。",
      "它既是自然地理描述，也是工程布置条件的一部分。",
      "帮助员工理解布置不是拍脑袋，而是受地形强约束。",
      1,
      "geology-report",
      "属于勘察报告",
    ),
    baseNode(
      "lithology",
      "地层岩性",
      "章节",
      "geology",
      2,
      -0.5,
      1.3,
      "解释不同岩石类型、结构构造和风化状态，是围岩判断基础。",
      "常见重点包括片麻岩、花岗斑岩等岩性及其工程意义。",
      "让岩石名称与工程判断建立直接联系。",
      2,
      "geology-report",
      "属于勘察报告",
    ),
    baseNode(
      "faults",
      "构造与断裂",
      "章节",
      "geology",
      2,
      -0.1,
      3.3,
      "说明区域构造背景和局部断裂发育情况。",
      "它不是单纯的地质名词，而是工程风险的重要触发条件。",
      "帮助员工从地质描述进入工程风险判断。",
      1,
      "geology-report",
      "属于勘察报告",
    ),
    baseNode(
      "hydrogeology",
      "水文地质",
      "章节",
      "geology",
      2,
      1.4,
      0.4,
      "关注地下水补给、径流、排泄和岩体透水性。",
      "它是理解渗漏、外水压力与防渗设计的关键章节。",
      "能把地层、构造和水的逻辑真正串起来。",
      1,
      "geology-report",
      "属于勘察报告",
    ),

    baseNode(
      "dam-site",
      "坝址条件",
      "概念",
      "engineering",
      3,
      0.9,
      -3.2,
      "把地形地貌与工程布置联系起来的关键概念。",
      "帮助理解为何某个位置适合布置坝体以及需要重点评价什么。",
      "是从地貌描述过渡到工程选择的重要节点。",
      0,
      "upper-reservoir",
      "属于上水库",
    ),
    baseNode(
      "reservoir-leakage",
      "水库渗漏",
      "工程地质问题",
      "engineering",
      3,
      2.6,
      -2.0,
      "上、下水库评价中的重要风险点。",
      "常与断裂、透水性、水文地质和防渗设计一起分析。",
      "能把构造、水文、工程部位三条线汇到一个问题上。",
      0,
      "upper-reservoir",
      "属于上水库",
    ),

    baseNode(
      "gneiss",
      "片麻岩",
      "岩性",
      "geology",
      3,
      2.5,
      1.7,
      "项目资料中的重要岩性之一，需要结合结构面和风化状态看工程性质。",
      "在地下厂房围岩评价中，它往往是绕不过去的核心实体。",
      "帮助员工把岩石名字与工程判断联系起来。",
      0,
      "underground-powerhouse",
      "围岩相关",
    ),
    baseNode(
      "fault-zone",
      "断裂构造",
      "构造",
      "geology",
      3,
      3.4,
      3.2,
      "对地下洞室稳定、库区渗漏和边坡安全都可能有控制作用的关键构造现象。",
      "它不是所有问题的根源，但通常是必须优先关注的实体。",
      "理解断裂后，很多工程问题都会变得有因可循。",
      0,
      "underground-powerhouse",
      "构造相关",
    ),
    baseNode(
      "stability",
      "围岩稳定",
      "工程地质问题",
      "engineering",
      3,
      4.2,
      0.2,
      "地下厂房与洞室设计中的核心工程地质问题之一。",
      "需要综合岩性、断裂、地应力与地下水共同判断。",
      "它是“地质知识如何变成设计约束”的关键节点。",
      0,
      "underground-powerhouse",
      "属于地下厂房",
    ),
    baseNode(
      "stress",
      "地应力",
      "专题概念",
      "engineering",
      3,
      3.0,
      -1.4,
      "地下工程稳定分析的重要背景参数。",
      "常用于判断大洞室围岩行为、变形以及岩爆倾向。",
      "帮助员工把试验数据与实际工程判断连接起来。",
      0,
      "underground-powerhouse",
      "属于地下厂房",
    ),

    baseNode(
      "slope-stability",
      "边坡稳定",
      "工程地质问题",
      "engineering",
      2,
      0.8,
      4.8,
      "地表工程和库岸边坡评价中的典型问题。",
      "经常和地形地貌、断裂发育、风化条件一起分析。",
      "是项目风险视角里的重要分支。",
      0,
      "project-risks",
      "属于项目风险",
    ),
    baseNode(
      "external-water",
      "外水压力",
      "工程地质问题",
      "engineering",
      2,
      3.0,
      4.9,
      "洞室与地下结构评价中的重要问题之一。",
      "它通常由水文地质条件与结构位置共同决定。",
      "帮助理解地下工程与地下水系统如何相互作用。",
      0,
      "project-risks",
      "属于项目风险",
    ),

    baseNode(
      "liaodong-uplift",
      "辽东台隆",
      "区域构造单元",
      "regional",
      2,
      -10.0,
      4.5,
      "项目所在更大尺度的构造背景单元之一。",
      "区域构造背景影响项目所在区域的断裂发育、地层组合与地貌特征。",
      "帮助员工建立从区域到场地的尺度认知。",
      0,
      "regional-geology",
      "属于区域背景",
    ),
    baseNode(
      "landform-unit",
      "山地沟谷地貌",
      "区域地貌",
      "regional",
      2,
      -10.6,
      1.6,
      "项目区常见的地貌框架之一，用来解释高差、坡体和沟谷分布。",
      "它与水库布置、交通洞和边坡条件都有联系。",
      "让自然地貌与工程布置之间建立直接关系。",
      0,
      "regional-geology",
      "属于区域背景",
    ),
    baseNode(
      "fracture-system",
      "区域断裂系统",
      "区域构造",
      "regional",
      2,
      -9.1,
      -0.1,
      "比单个断裂更高层级的区域构造认识。",
      "有助于理解局部断裂不是孤立现象，而是区域构造系统的一部分。",
      "是把局部工程问题放回大背景的关键节点。",
      0,
      "regional-geology",
      "属于区域背景",
    ),

    baseNode(
      "fuxin-project",
      "阜新抽蓄项目",
      "项目",
      "mining",
      0,
      6.8,
      2.6,
      "第二个项目集群，用于表现画布可同时容纳多个项目而不乱。",
      "未来这里可以接入另一个真实知识库，实现多项目对照学习。",
      "现在它主要是验证 UI 不只适合单项目。",
      3,
    ),
    baseNode(
      "fuxin-report",
      "阜新可研资料",
      "文档",
      "mining",
      1,
      8.1,
      1.0,
      "阜新项目的总览文档入口。",
      "将来可以接入真实项目资料，形成与庄河项目平行的知识分支。",
      "验证多项目文档入口的统一交互。",
      1,
      "fuxin-project",
      "属于项目文档",
    ),
    baseNode(
      "fuxin-risks",
      "阜新风险专题",
      "专题",
      "mining",
      1,
      8.9,
      4.0,
      "阜新项目的风险入口节点。",
      "未来可以承载阜新项目的边坡、渗漏、断裂等问题。",
      "便于不同项目之间做专题对比学习。",
      0,
      "fuxin-project",
      "属于项目专题",
    ),
    baseNode(
      "fuxin-landform",
      "阜新场地地貌",
      "章节",
      "mining",
      2,
      10.2,
      2.5,
      "阜新项目的场地地貌节点，占位表示第二个项目集群也能自然展开。",
      "主要用于证明画布可以同时容纳多个项目簇。",
      "帮助评估多项目同屏时的观感。",
      0,
      "fuxin-report",
      "属于项目章节",
    ),
  ];

  const edges: KnowledgeEdge[] = [
    edge("e1", "zhuanghe-project", "feasibility-report", "包含"),
    edge("e2", "zhuanghe-project", "geology-report", "包含"),
    edge("e3", "zhuanghe-project", "upper-reservoir", "包含"),
    edge("e4", "zhuanghe-project", "underground-powerhouse", "包含"),
    edge("e5", "zhuanghe-project", "project-risks", "关联"),
    edge("e6", "zhuanghe-project", "regional-geology", "位于背景中"),
    edge("e7", "feasibility-report", "project-layout", "包含"),
    edge("e8", "feasibility-report", "construction-conditions", "包含"),
    edge("e9", "feasibility-report", "scheme-comparison", "包含"),
    edge("e10", "geology-report", "topography", "包含"),
    edge("e11", "geology-report", "lithology", "包含"),
    edge("e12", "geology-report", "faults", "包含"),
    edge("e13", "geology-report", "hydrogeology", "包含"),
    edge("e14", "upper-reservoir", "dam-site", "关注"),
    edge("e15", "upper-reservoir", "reservoir-leakage", "关注"),
    edge("e16", "underground-powerhouse", "gneiss", "围岩为"),
    edge("e17", "underground-powerhouse", "fault-zone", "受影响"),
    edge("e18", "underground-powerhouse", "stability", "存在问题"),
    edge("e19", "underground-powerhouse", "stress", "分析依据"),
    edge("e20", "project-risks", "stability", "包含"),
    edge("e21", "project-risks", "reservoir-leakage", "包含"),
    edge("e22", "project-risks", "slope-stability", "包含"),
    edge("e23", "project-risks", "external-water", "包含"),
    edge("e24", "regional-geology", "liaodong-uplift", "包含"),
    edge("e25", "regional-geology", "landform-unit", "包含"),
    edge("e26", "regional-geology", "fracture-system", "包含"),
    edge("e27", "topography", "dam-site", "影响"),
    edge("e28", "lithology", "gneiss", "重点概念"),
    edge("e29", "faults", "fault-zone", "重点概念"),
    edge("e30", "hydrogeology", "reservoir-leakage", "支撑判断"),
    edge("e31", "fault-zone", "reservoir-leakage", "影响"),
    edge("e32", "fault-zone", "stability", "影响"),
    edge("e33", "gneiss", "stability", "影响"),
    edge("e34", "construction-conditions", "project-risks", "关联"),
    edge("e35", "regional-geology", "fault-zone", "背景控制"),
    edge("e36", "fuxin-project", "fuxin-report", "包含"),
    edge("e37", "fuxin-project", "fuxin-risks", "关联"),
    edge("e38", "fuxin-report", "fuxin-landform", "包含"),
  ];

  return { nodes, edges };
};
